Bridge.assembly("TestProject", function ($asm, globals) {
    "use strict";


    var $m = Bridge.setMetadata,
        $n = [System,TestProject1,TestProject2,Issue3278,Issue3276,N3208_1_AndreyReview1,Issue2493];
    $m($n[1].TestClassA, function () { return {"att":1048576,"a":4,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Value1","t":16,"rt":$n[0].Int32,"g":{"a":2,"n":"get_Value1","t":8,"rt":$n[0].Int32,"fg":"Value1","box":function ($v) { return Bridge.box($v, System.Int32);}},"s":{"a":2,"n":"set_Value1","t":8,"p":[$n[0].Int32],"rt":$n[0].Void,"fs":"Value1"},"fn":"Value1"}]}; });
    $m($n[2].TestClassB, function () { return {"att":1048576,"a":4,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Value1","t":16,"rt":$n[0].Int32,"g":{"a":2,"n":"get_Value1","t":8,"rt":$n[0].Int32,"fg":"Value1","box":function ($v) { return Bridge.box($v, System.Int32);}},"s":{"a":2,"n":"set_Value1","t":8,"p":[$n[0].Int32],"rt":$n[0].Void,"fs":"Value1"},"fn":"Value1"}]}; });
    $m($n[3].Program, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"TestProp","t":16,"rt":$n[0].String,"g":{"a":2,"n":"get_TestProp","t":8,"rt":$n[0].String,"fg":"TestProp"},"fn":"TestProp"}]}; });
    $m($n[4].Program, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Demo","is":true,"t":8,"pi":[{"n":"a","pt":$n[0].Byte,"ps":0},{"n":"b","pt":$n[0].Char,"ps":1},{"n":"c","pt":$n[0].Decimal,"ps":2},{"n":"d","pt":$n[0].Double,"ps":3},{"n":"e","pt":$n[0].Int16,"ps":4},{"n":"f","pt":$n[0].Int32,"ps":5},{"n":"g","pt":$n[0].Int64,"ps":6},{"n":"h","pt":$n[0].SByte,"ps":7},{"n":"i","pt":$n[0].UInt16,"ps":8},{"n":"j","pt":$n[0].UInt32,"ps":9},{"n":"k","pt":$n[0].UInt64,"ps":10}],"sn":"Demo","rt":$n[0].Void,"p":[$n[0].Byte,$n[0].Char,$n[0].Decimal,$n[0].Double,$n[0].Int16,$n[0].Int32,$n[0].Int64,$n[0].SByte,$n[0].UInt16,$n[0].UInt32,$n[0].UInt64]}]}; });
    $m($n[5].App, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Main","is":true,"t":8,"sn":"Main","rt":$n[0].Void}]}; });
    $m(Operation, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Add","t":8,"pi":[{"n":"a","pt":$n[0].Int32,"ps":0},{"n":"b","pt":$n[0].Int32,"ps":1}],"sn":"Add","rt":$n[0].Int32,"p":[$n[0].Int32,$n[0].Int32],"box":function ($v) { return Bridge.box($v, System.Int32);}}]}; });
    $m(o2, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Add","t":8,"pi":[{"n":"a","pt":$n[0].Int32,"ps":0},{"n":"b","pt":$n[0].Int32,"ps":1}],"sn":"Add","rt":$n[0].Int32,"p":[$n[0].Int32,$n[0].Int32],"box":function ($v) { return Bridge.box($v, System.Int32);}}]}; });
    $m($n[6].Operation3, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Add","t":8,"pi":[{"n":"a","pt":$n[0].Int32,"ps":0},{"n":"b","pt":$n[0].Int32,"ps":1}],"sn":"Add","rt":$n[0].Int32,"p":[$n[0].Int32,$n[0].Int32],"box":function ($v) { return Bridge.box($v, System.Int32);}}]}; });
});
